$schema: http://json-schema.org/draft-04/schema
id: http://asyncapi.com/definitions/1.2.0/parameters.json
type: object
additionalProperties:
  $ref: ../fragments/parameter.yaml
description: JSON objects describing re-usable topic parameters.
