$schema: http://json-schema.org/draft-04/schema#
type: object
additionalProperties: false
required:
  - type
properties:
  type:
    type: string
    enum:
      - basic
  description:
    type: string
patternProperties:
  ^x-:
    $ref: ./vendorExtension.yaml
