$schema: http://json-schema.org/draft-04/schema#
type: object
additionalProperties: false
required:
  - type
  - flow
  - tokenUrl
properties:
  type:
    type: string
    enum:
      - oauth2
  flow:
    type: string
    enum:
      - password
  scopes:
    $ref: ./oauth2Scopes.yaml
  tokenUrl:
    type: string
    format: uri
  description:
    type: string
patternProperties:
  ^x-:
    $ref: ./vendorExtension.yaml
